Program CALCULADORA;
Var N1,N2,RES:real;
		OP:string[1];
Begin
	// SOLICITA VALORES AO USUÁRIO
  WRITELN('DIGITE O PRIMEIRO NÚMERO');
  READLN(N1);
  WRITELN('DIGITE O SEGUNDO NÚMERO');
  READLN(N2);
  WRITELN('DIGITE O TIPO DE OPERAÇÃO A SER REALIZADA');
  WRITELN('ADIÇÃO: +');
  WRITELN('SUBTRAÇÃO: -');
  WRITELN('MULTIPLICAÇÃO: *');
  WRITELN('DIVISÃO: /');
	READLN(OP);
	
	// REALIZA O CALCULO
			//SOMA
	IF (OP='+') THEN 
		RES := N1+N2
	ELSE
		  //SUBTRAÇAO
		IF (OP='-') THEN
			RES := N1-N2
		ELSE
			//MULTIPLICAÇAO
			IF(OP='*') THEN
				RES := N1*N2
			ELSE
			//DIVISAO
				IF(OP='/') THEN
					//DENOMINADOR É ZERO
					IF(N2=0) THEN
						WRITELN('ERRO')
					ELSE
					//DENOMINADOR É DIFERENTE DE ZERO
						RES := N1/N2;
	
	// MOSTRA RESULTADO
		WRITELN(N1:2:2, OP, N2:2:2, '=', RES:2:2);
		WRITELN;
		WRITELN('ENTER PARA ENCERRAR');
		READLN;
End.
